config/routes.rb
Rails.application.routes.draw do

  root to: 'projects#index'
  
  resources :projects do
    resources :tasks
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user


def color
    case status
      when 'not-started'
        'primary'
      when 'in-progress'
        'info'
      else 'complete'
        'success'      
    end
  end

def status 

  return 'complete' if ((total_complete.to_f / total_tasks) * 100) == 100

  if tasks.any? { |task| task.complete? || task.in_progress?} 
    'in-progress'
  else
    'not-started'
      
  end
end

def percent_complete

  return 0 if total_tasks == 0

  ((total_complete.to_f / total_tasks) * 100).round(1)
end

def total_complete
  tasks.select { |task| task.complete? }.count
end

def total_tasks
  tasks.count
end



end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: {in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
]

  def color
    case status
      when 'not-started'
        'primary'
      when 'in-progress'
        'info'
      when 'complete'
        'success'      
    end
  end


  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projects</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    
      <nav class="navbar navbar-light bg-light">
        <div class="container">
          <div class="navbar-header">
            <%= link_to 'Project App', root_path, class: 'navbar-brand' %>
            
              <div id="navbar d-flex justify-content-between">
                <ul class="nav navbar-nav ">
                  <% if user_signed_in? %>
                  <%= current_user.email %>
                    <li><%= link_to 'Sign Out', destroy_user_session_path,   :method => :delete, 
                    class: 'btn btn-primary btn-md ' %></li>
                  
                  <% else %>
                    
                    <li><%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary btn-md'%></li><br>
                    <li><%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-md' %></li>
                </ul>
                  <% end %>

                </ul>
            </div>  
          </div>
        </div>
      </nav>
              
          <div class='container '> 
              <div>
                <p class=" notice "><%= notice %></p>
                <p class=" alert"><%= alert %></p>
              </div> 
            <%= yield %>
          </div>
     

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group w-50">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group w-50">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div><br>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3 ' %>
<div class='card w-75 '>
  <div class='card-body'>
    <h2 class='card-title  mb-4'>
        <span>Edit Project</spam>
    </h2>
        <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<div class='card '>
  <div class='card-body'>

      <h2 class='card-title d-flex justify-content-between mb-4'>
        <span>Projects</span>
        <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
      </h2>


      <% @projects.each do |project| %>
        <%= link_to project, class: 'text-decoration-none' do %>
          <div class='card project-card mb-6'>
            <div class='card-body'>
              
              <h4 class='card-title text-dark' ><%= project.name %></h4>
        <% end %>
          <h5 class='text-secondary'><%= project.description %></h5>
            <div class='mb-3'>     
              <span class="bg-<%= project.color %> text-white "><%= project.status %>   
                  </span>
              <span class='text-secondary'>  
                  <small class='m-2'>
                    <%= project.percent_complete %> % task completed
                    (<%= project.total_complete %> / <%= project.total_tasks %> tasks)
                  </small>
              </span>
            </div>

            </div>
          </div><br>
        
      <% end %>

      
    </div>
  </div>

app/views/projects/new.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3 ' %>
<div class='card w-75 '>
  <div class='card-body'>
    <h2 class='card-title  mb-4'>
        <span>New Project</spam>
    </h2>
        <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-light mb-4' %>

<div class='card'>
  <div class='card-body'>
    <h2 class='card-title d-flex justify-content-between mb-2'>
        
        <span><%= @project.name %></span>
        <div>
          <%= link_to 'Edit', edit_project_path, class: 'btn btn-warning' %>
          <%= link_to 'Destroy', @project, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
        </div>
    </h2>
    <div class='mb-3 '><h3><%= @project.description %></h3></div>

    <h5>Add task</h5>

    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>



    
    <%= form_for([@task.project, @task]) do |f| %>
        <div class='input-group'>
            <%= f.text_field :name, class:'form-control', placeholder: 'Enter task name...' %> 
            <%= f.text_field :description, class:'form-control', placeholder: 'Enter task description...' %> 
            <%= f.hidden_field :status, value: 'not-started' %>
          <div class="input-group-primary">
            <%= f.submit class: 'btn btn-primary'%>
          </div>
        </div><br>
    <% end %>

     <hr> 

    <h3 class='mt-2'>Tasks</h3>

    <% @project.tasks.each do |task| %>
      <% if task.persisted? %>
        <div class='card task-card mb-4' >

            <div class='card-body' >    
               
                <h2 class='card-title d-flex justify-content-between mb-2'>      
                     
                      <span class=" mb-3 bg-<%= task.color %> text-white btn btn-danger btn-sm"> <%= task.status %></span>

                      <div>        
                      <%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-warning btn-sm' %>
                      <%= link_to 'Destroy', [task.project, task], method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %>
                      </div>
                </h2>
                
                <span><h3><%= task.name %></h3></span>               
              <h5><%= task.description %></h5>
              
            </div>

        </div>

      <% end %>
      
    <% end %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group w-50">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  <div class="form-group w-50">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group w-50">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_OPTIONS, class: 'form-control' %>
  </div><br>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3 ' %>
<div class='card w-75 '>
  <div class='card-body'>
    <h2 class='card-title  mb-4'>
        <span>Edit task</spam>
    </h2>
        <%= render 'form', project: @project %>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3 ' %>
<div class='card w-75 '>
  <div class='card-body'>
    <h2 class='card-title  mb-4'>
        <span>New Project</spam>
    </h2>
        <%= render 'form' %>
  </div>
</div>







<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>